### ISSUE TITLE
[1.19.2] Incompatibility with 'Snow! Real Magic!' GameRules

### ISSUE THREAD

**Issue by JLUsr** [EnnuiL/BoringDefaultGameRules#4] opened 2023-02-10 01:53 UTC
So I seem to be getting a launch failure and config wipe when setting any default gamerule for [Snow! Real Magic!](https://www.curseforge.com/minecraft/mc-mods/snow-real-magic-/files/4104368) The following [gist](https://gist.github.com/JLUsr/12e8e7668b7e299c0e1396b3fd7d26f9) is the relevant information printed by the log during launch when setting `blizzardFrequency` to `0`.

**Comment by EnnuiL** [comment] 2023-03-24 02:05
Consider this a duplicate of #3, you've used a number value and that unfortunately turned out to make things go haywire; This will be fixed on an upcoming 1.19.4 and 1.19.2 update

**Closed as completed by EnnuiL** 2023-03-24 02:05 UTC
Labels: bug
